<?php

// This is the main Web application configuration. Any writable
// application properties can be configured here.
return array(
    'basePath'   => dirname( __FILE__ ) . DIRECTORY_SEPARATOR . '..',
    'name'       => 'Birthday',
    'modules'    => array(
        'gii' => array(
            'class'     => 'system.gii.GiiModule',
            'password'  => '111111',
            'ipFilters' => array( '109.167.253.77' ),
            // 'newFileMode'=>0666,
            // 'newDirMode'=>0777,
        ),
    ),
    'import'     => array(
        'application.components.ImageHandler.CImageHandler',
        'ext.sessionstorage.*',
        'ext.PHPExcel.*',
        //'ext.phpconsole.PhpConsoleLogRoute.*'

    ),
    'preload' => array('Log'),
    'components' => array(
        'session'    => array(
            'class'   => 'UserHttpSession',
            'storage' => array(
                'class'        => 'SQLSessionStorage',
                'connectionID' => 'db',
            ),
        ),

        'Log' => array(
            'class' => 'CLogRouter',
             'routes' => array (
                'class' => 'ext.phpconsole.PhpConsoleLogRoute',
                 /* Параметры по умолчанию:
                'IsEnabled' => true,
                'HandleErrors' => true,
                'HandleExceptions' => true,
                'SourcesBasePath' => $ _SERVER ['DOCUMENT_ROOT'],
                'PhpConsolePathAlias' => 'application.vendors.PhpConsole.src.PhpConsole',
                'RegisterHelper' => true,
                'ServerEncoding' => null,
                'HeadersLimit' => null,
                'Password' => null,
                'EnableSslOnlyMode' => false,
                'IpMasks' => array (),
                'DumperLevelLimit' => 5,
                'DumperItemsCountLimit' => 100,
                'DumperItemSizeLimit' => 5000,
                'DumperDumpSizeLimit' => 500000,
                'DumperDetectCallbacks' => true,
                'DetectDumpTraceAndSource' => true,
                'IsEvalEnabled' => false,
                */
            )
        ),
        'db'         => array(

            'connectionString' => 'mysql:host=localhost;dbname=a0009865_qpkuhni',
            'username'         => 'a0009865_a000986',
            'password'         => 'ihamwaimhi',
            'charset'          => 'utf8',

        /*
                'connectionString' => 'mysql:host=localhost;dbname=a0009865_test',
                'username'         => 'a0009865_test',
                'password'         => 'test',
                'charset'          => 'utf8',
        */
        ),
        'urlManager' => array(
            'urlFormat'      => 'path',
            'showScriptName' => false,
            'caseSensitive'  => false,
            'rules'          => array(
                //new catalog
                'catalog/'                             => 'catalog/index',
                //'catalog/folder/<id>'                 => 'catalog/folder',
                'catalog/stoleshnicy'                 => 'catalog/folder/8',
                'catalog/kuhonnye-aksessuary/<id>'    => 'catalog/kuhonnyeaksessuary',
                'catalog/stenovye-paneli/<id>'        => 'catalog/stenovyepaneli',
                'catalog/stoleshnicy/<id>'            => 'catalog/stoleshnicy',
                'catalog/kuhonnaya-tehnika/<id>'      => 'catalog/kuhonnayatehnika',
                'kak-vybrat-kuhnyu'         		  => 'site/kakvybratkuhnyu',
                'kak-kupit-kuhnyu-nedorogo'			  => 'site/kakkupitkuhnyunedorogo',
                'gotovye-kuhni'						  => 'site/gotovyekuhni',
                'gotovye-kuhni/<categ>'               => 'site/gotovyekuhni',
				'katalog-kuhon'						  => 'site/katalogkuhon',
                //'katalog-kuhon/<categ>'               => 'site/katalogkuhon',
                //catalog
//				'catalog'                             => 'catalog/index',
                'catalog/accessories/'                 => 'catalog/accessories',
                'catalog/accessory/<id>/'              => 'catalog/accessory',
                'catalog/equipment'                   => 'catalog/equipment',
                'catalog/equipment/<id>'              => 'catalog/equipmentItem',
                'catalog/tabletops'                   => 'catalog/tabletops',
                'catalog/tabletop/<id>'               => 'catalog/tabletop',
                'catalog/wall-panels'                 => 'catalog/wallpanels',
                'catalog/wall-panel/<id>'             => 'catalog/wallpanel',
                'catalog/bars'                        => 'catalog/bars',
                'catalog/bar/<id>'                    => 'catalog/barItem',
				'catalog/shkafy'                      => 'catalog/404',
				'catalog/shkafy/<id>'                 => 'catalog/shkafy',
                'catalog/shkaf/<id>'                  => 'catalog/shkaf',
                'catalog/fronts'                      => 'catalog/fronts',
                'catalog/front/<id>'                  => 'catalog/front',
                'catalog/kitchenmodules'              => 'catalog/kitchenmodules',
                'catalog/setKitchenModuleColor'       => 'catalog/setKitchenModuleColor',
                'catalog/moduleItem/<id>'             => 'catalog/moduleItem',
                'kitchen-module'                      => 'catalog/kitchenModule',
                'kitchen-modules-color'               => 'catalog/kitchenModulesColor',
                'fronts-color'                        => 'catalog/frontsColor',
                'tabletops'                           => 'catalog/tabletops',
                'tabletop/<id>'                       => 'catalog/tabletop',
                'wall-panels'                         => 'catalog/wallpanels',
                'wall-panel/<id>'                     => 'catalog/wallPanel',
                'accessories'                         => 'catalog/accessories',
                'accessory/<id>'                      => 'catalog/accessory',
                'equipment'                           => 'catalog/equipment',
                'equipment-item/<id>'                 => 'catalog/equipmentItem',
                //'kitchens'                            => 'site/kitchens',
                //'kitchen/<id>'                        => 'site/kitchen',
				'kitchen/<url:[\w\-]+>'               => 'site/kitchen',
                'how-to'                              => 'site/howToOrder',
                'delivery'                            => 'site/deliveryAndAssembly',
                'about'                               => 'site/aboutManufacture',
                'action'                              => 'site/action',
                'fasady-ldsp'                         => 'site/fasadyldsp',
                'fasad-mdf'                           => 'site/fasadmfd',
                'fasady-plastik'                      => 'site/fasadyplastik',
                'contacts'                            => 'site/contacts',
                'kuhni-na-zakaz'                      => 'site/kuhnizakaz',
                'review'                              => 'site/review',
                'add/review'                          => 'site/addReview',
                'advantage'                           => 'site/advantage',
                'whyorder/<id>'                       => 'site/whyorder',
                'polezno-znat/<url:[\w\-]+>'          => 'site/poleznoznat',
                'polezno-znat'                        => 'site/poleznoznat',
                'news'                                => 'site/news',
                'NewsItem/<id>'                       => 'site/NewsItem',
                'cheaper'                             => 'site/cheaper',
                'cheaperItem/<id>'                    => 'site/cheaperItem',
                'howorder'                            => 'site/howorder',
                'howorder-link/<id>'                  => 'site/howorderLink',
                'nashi-dekory'                        => 'site/nashidekory',
                'nashi-dekory-id/<url:[\w\-]+>'       => 'site/nashidekoryid',
				'nashi-raboty'                        => 'site/nashiraboty',
                'sitemap'                             => 'site/sitemap',
                'sign-up'                             => 'user/signUp',
                'sign-in'                             => 'user/signIn',
                'sign-out'                            => 'user/signOut',
                //user
                'profile'                             => 'user/profile',
                'profile/orders'                      => 'user/orders',
                'profile/order/<id>'                  => 'user/order',
                'result.php'                          => 'user/oplata',
                // shopping cart
                'shopping-cart/accessory/add'         => 'shop/addAccessory',
                'shopping-cart/equipment/add'         => 'shop/addEquipment',
                'shopping-cart/cover/add'             => 'shop/addCover',
                'shopping-cart/save'                  => 'shop/shoppingCartSave',
                'shopping-cart/load/<id>'             => 'shop/shoppingCartLoad',
                'shopping-cart/remove/<id>'           => 'shop/shoppingCartRemove',
                'shopping-cart/list'                  => 'shop/shoppingCarts',
                'shopping-cart/clear'                 => 'shop/shoppingCartClear',
                // shop
                'add/module'                          => 'shop/addModuleToShoppingCart',
                'add/front'                           => 'shop/addFrontToShoppingCart',
                'add/tabletop'                        => 'shop/addTabletopToShoppingCart',
                'shop/remove/item/<id>'               => 'shop/removeItem',
                'shop/edit/item/<id>'                 => 'shop/editItem',
                'shop/update/cover'                   => 'shop/addCover',
                'shop/update/accessory'               => 'shop/addAccessory',
                'shop/update/equipment'               => 'shop/addEquipment',
                'shop/update/module'                  => 'shop/addModuleToShoppingCart',
                'shop/update/front'                   => 'shop/addFrontToShoppingCart',
                'shopping-cart'                       => 'shop/shoppingCart',
                'shopping-cart/update'                => 'shop/shoppingCartUpdate',
                'ordering'                            => 'shop/ordering',
                // admin

                'admin'                               => 'admin/admin/dashboard',
                'admin/pages'                         => 'admin/page/view',
                'admin/page/edit/<id:d+>'             => 'admin/page/edit',
                'admin/actions'                       => 'admin/action/view',
                'admin/action/edit/<id:d+>'           => 'admin/action/edit',
                'admin/slider'                        => 'admin/slider/view',
                'admin/slider/edit/<id:d+>'           => 'admin/slider/edit',
                'admin/catalog-menu'                  => 'admin/catalogmenu/view',
                'admin/catalog-menu/edit/<id>'        => 'admin/catalogmenu/edit',
                'admin/catalog-menu/save'             => 'admin/catalogmenu/save',

                'admin/advantages'                 => 'admin/advantages/view',
                'admin/advantages/create'          => 'admin/advantages/create',
                'admin/advantages/delete'          => 'admin/advantages/delete',


                'admin/seo'                            => 'admin/seo/view',
                'admin/seo/create'                     => 'admin/seo/create',
                'admin/seo/delete'                   => 'admin/seo/delete',

                'admin/running-meter'                 => 'admin/runningmeter/view',
                'admin/running-meter/create'          => 'admin/runningmeter/create',
                'admin/running-meter/delete'          => 'admin/runningmeter/delete',
                'admin/running-meter/edit'            => 'admin/runningmeter/edit',
                'admin/running-meter/edit/<id:d+>'    => 'admin/runningmeter/edit',
                'admin/kitchens'                      => 'admin/kitchens/view',
                'admin/kitchens/edit/<id:d+>'         => 'admin/kitchens/edit',
                'admin/colors'                        => 'admin/color/view',
                'admin/color/edit/<id:d+>'            => 'admin/color/edit',
                'admin/frez'                          => 'admin/frez/view',
                'admin/frez/edit/<id:d+>'             => 'admin/frez/edit',
                'admin/kitchens/edit/<id:d+>'         => 'admin/kitchens/edit',
                //options
                'admin/module-options'                => 'admin/moduleoptions/view',
                'admin/module-option/edit'            => 'admin/moduleoptions/edit',
                'admin/module-option/delete'          => 'admin/moduleoptions/delete',
                'admin/module-option/create'          => 'admin/moduleoptions/create',
                'admin/module-option/save'            => 'admin/moduleoptions/save',
                //modules
                'admin/item-modules'                  => 'admin/itemmodules/view',
                'admin/item-module/edit/<id>'         => 'admin/itemmodules/edit',
                'admin/item-module/delete/<id>'       => 'admin/itemmodules/delete',
                'admin/item-module/create'            => 'admin/itemmodules/create',
                'admin/item-module/save'              => 'admin/itemmodules/save',
                //fronts
                'admin/item-fronts'                   => 'admin/itemfronts/view',
                'admin/item-front/edit/<id>'          => 'admin/itemfronts/edit',
                'admin/item-front/delete/<id>'        => 'admin/itemfronts/delete',
                'admin/item-front/create'             => 'admin/itemfronts/create',
                'admin/item-front/save'               => 'admin/itemfronts/save',
                //covers
                'admin/item-covers'                   => 'admin/itemcovers/view',
                'admin/item-covers/edit/<id>'         => 'admin/itemcovers/edit',
                'admin/item-covers/delete/<id>'       => 'admin/itemcovers/delete',
                'admin/item-covers/create'            => 'admin/itemcovers/create',
                'admin/item-covers/save'              => 'admin/itemcovers/save',
                //folders
                'admin/folders'                       => 'admin/folders/view',
                'admin/folders/edit/<id>'             => 'admin/folders/edit',
                'admin/folders/delete/<id>'           => 'admin/folders/delete',
                'admin/folders/create'                => 'admin/folders/create',
                'admin/folders/save'                  => 'admin/folders/save',
                //accessories
                'admin/item-accessories'              => 'admin/itemaccessories/view',
                'admin/item-accessories/edit/<id>'    => 'admin/itemaccessories/edit',
                'admin/item-accessories/delete/<id>'  => 'admin/itemaccessories/delete',
                'admin/item-accessories/create'       => 'admin/itemaccessories/create',
                'admin/item-accessories/save'         => 'admin/itemaccessories/save',
                //equipment
                'admin/item-equipment'                => 'admin/itemequipment/view',
                'admin/item-equipment/edit/<id>'      => 'admin/itemequipment/edit',
                'admin/item-equipment/delete/<id>'    => 'admin/itemequipment/delete',
                'admin/item-equipment/create'         => 'admin/itemequipment/create',
                'admin/item-equipment/save'           => 'admin/itemequipment/save',
                //equipment
                'admin/orders'                        => 'admin/order/view',
                'admin/order/edit/<id>'               => 'admin/order/edit',
                'admin/order/delete/<id>'             => 'admin/order/delete',
                'admin/order/create'                  => 'admin/order/create',
                'admin/order/save'                    => 'admin/order/save',
				'admin/order/download/<id>'           => 'admin/order/download',
                'admin/price'                         => 'admin/price/view',
                'admin/frontPrice'                    => 'admin/price/frontPrice',
                'admin/saveFrontPrice'                => 'admin/price/saveFrontPrice',
                'admin/modulePrice'                   => 'admin/price/modulePrice',
                'admin/equipmentPrice'                => 'admin/price/equipmentPrice',
                'admin/price/reloadPrice'             => 'admin/price/reloadPrice',
                'admin/reviews'                       => 'admin/review/view',
                'admin/reviews/edit/<id:d+>'          => 'admin/reviews/edit',
                'admin/polezno-znat/edit/<id:d+>'     => 'admin/poleznoznat/edit',
                'admin/polezno-znat'                  => 'admin/poleznoznat/view',
                'admin/polezno-znat/create'           => 'admin/poleznoznat/create',
                'admin/polezno-znat/delete/<id:d+>'   => 'admin/poleznoznat/delete',
                'admin/polezno-znat/edit/<id:d+>'     => 'admin/poleznoznat/edit',
                'admin/news'                          => 'admin/news/view',
                'admin/news/edit/<id:d+>'             => 'admin/news/edit',
                'admin/our-colors'                    => 'admin/ourcolors/view',
                'admin/our-colors/create'             => 'admin/ourcolors/create',
                'admin/our-colors/delete/<id>'        => 'admin/ourcolors/delete',
                'admin/our-colors/edit/<id>'          => 'admin/ourcolors/edit',
                'admin/our-colors/save'               => 'admin/ourcolors/save',
                'admin/our-colors/addcolor'           => 'admin/ourcolors/addcolor',
                'admin/cheaper'                       => 'admin/cheaper/view',
                'admin/cheaper/edit/<id:d+>'          => 'admin/cheaper/edit',
                'admin/howorder'                      => 'admin/howorder/view',
                'admin/howorder/edit/<id:d+>'         => 'admin/howorder/edit',
                'admin/whyorder'                      => 'admin/whyorder/view',
                'admin/whyorder/edit/<id:d+>'         => 'admin/whyorder/edit',
                'admin/nashiraboty'                   => 'admin/nashiraboty/edit',
				'admin/nashiraboty/save'              => 'admin/nashiraboty/save',
				'admin/cupboard'                      => 'admin/cupboard/view',
				'admin/cupboard/edit/<id:d+>'   	  => 'admin/cupboard/edit',


                'ajax/fronts'                         =>'ajax/fronts',
                //'admin/<controller:w+>/<action:w+>/<id:d+>' => 'admin/<controller>/<action>',
                '<controller:w+>/<action:w+>/<id:d+>' => '<controller>/<action>',
                '<controller:w+>/<action:w+>'         => '<controller>/<action>'
            ),
        ),
        'ih'         => array('class'=>'CImageHandler'),
        'user'       => array(
            // enable cookie-based authentication
            'allowAutoLogin' => true,
        ),
    ),

);